spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistics?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Zry_123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    pool:
     max-active: 300
     min-idle: 0
     max-wait: 10000
     max-idle: 100
     timeout: 5000
    host: localhost
    password: 123456
    database: 15
    port: 6379
ftp:
  clientTimeout: 10000
  encoding: UTF-8
  passiveMode: true
  host: localhost
  port: 21
  username: admin
  password: 123456

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

###视频上传配置
oss:
  access_key_id:
  access_key_secret:
  bucket_name:
  end_point:

mapper:
    not-empty: false
    identity: MYSQL

upload:
  file:
    dir: /home/admin/tmp